# ─── Centralized PROD Profile Properties (Served from Config Server) ──────────
app.environment=CENTRALIZED_PRODUCTION
logging.level.com.example.employeemanagement=INFO
server.port=8080
spring.datasource.url=jdbc:h2:file:./data/employeedb_prod
